var stringToArrayBuffer=function(a){for(var b=new Uint8Array(a.length),c=0;c<a.length;c++)b[c]=a.charCodeAt(c);return b.buffer},base64ToArrayBuffer=function(a){return stringToArrayBuffer(atob(a))};function massageMessageNativeToJs(a){"ArrayBuffer"==a.CDVType&&(a=base64ToArrayBuffer(a.data));return a}function convertToNativeJS(a){Object.keys(a).forEach(function(b){var c=a[b];a[b]=massageMessageNativeToJs(c);"object"===typeof c&&convertToNativeJS(c)})}
BLEPluginStd.prototype={scan:function(a,b,c,d){cordova.exec(function(a){convertToNativeJS(a);c(a)},d,"BLE","scan",[a,b])},startScan:function(a,b,c){cordova.exec(function(a){convertToNativeJS(a);b(a)},c,"BLE","startScan",[a])},stopScan:function(a,b){cordova.exec(a,b,"BLE","stopScan",[])},startScanWithOptions:function(a,b,c,d){b=b||{};cordova.exec(function(a){convertToNativeJS(a);c(a)},d,"BLE","startScanWithOptions",[a,b])},list:function(a,b){cordova.exec(a,b,"BLE","list",[])},connect:function(a,b,
c){cordova.exec(function(a){convertToNativeJS(a);b(a)},c,"BLE","connect",[a])},disconnect:function(a,b,c){cordova.exec(b,c,"BLE","disconnect",[a])},read:function(a,b,c,d,e){cordova.exec(function(a){var b;if(a&&a.length){b=[];for(var c=0;c<a.length;c++)b[c]=a[c]}else b=a;d&&d(b)},e,"BLE","read",[a,b,c])},readRSSI:function(a,b,c){cordova.exec(b,c,"BLE","readRSSI",[a])},write:function(a,b,c,d,e,f){console.log("BLEWRITE WITH");console.log(d);cordova.exec(e,f,"BLE","write",[a,b,c,d])},writeWithoutResponse:function(a,
b,c,d,e,f){cordova.exec(e,f,"BLE","writeWithoutResponse",[a,b,c,d])},writeCommand:function(a,b,c,d,e,f){console.log("WARNING: writeCommand is deprecated, use writeWithoutResponse");cordova.exec(e,f,"BLE","writeWithoutResponse",[a,b,c,d])},notify:function(a,b,c,d,e){console.log("WARNING: notify is deprecated, use startNotification");cordova.exec(d,e,"BLE","startNotification",[a,b,c])},startNotification:function(a,b,c,d,e){cordova.exec(d,e,"BLE","startNotification",[a,b,c])},stopNotification:function(a,
b,c,d,e){cordova.exec(d,e,"BLE","stopNotification",[a,b,c])},isConnected:function(a,b,c){cordova.exec(b,c,"BLE","isConnected",[a])},isEnabled:function(a,b){cordova.exec(a,b,"BLE","isEnabled",[])},enable:function(a,b){cordova.exec(a,b,"BLE","enable",[])},showBluetoothSettings:function(a,b){cordova.exec(a,b,"BLE","showBluetoothSettings",[])},startStateNotifications:function(a,b){cordova.exec(a,b,"BLE","startStateNotifications",[])},stopStateNotifications:function(a,b){cordova.exec(a,b,"BLE","stopStateNotifications",
[])}};function BLEPluginStd(){}
BLEPluginPromises.prototype={scan:BLEPluginStd.scan,startScan:BLEPluginStd.startScan,startScanWithOptions:BLEPluginStd.startScanWithOptions,connect:BLEPluginStd.connect,startNotification:BLEPluginStd.startNotification,startStateNotifications:BLEPluginStd.startStateNotifications,stopScan:function(){return new Promise(function(a,b){BLEPluginStd.stopScan(a,b)})},disconnect:function(a){return new Promise(function(b,c){BLEPluginStd.disconnect(a,b,c)})},read:function(a,b,c){return new Promise(function(d,
e){BLEPluginStd.read(a,b,c,d,e)})},write:function(a,b,c,d){return new Promise(function(e,f){BLEPluginStd.write(a,b,c,d,e,f)})},writeWithoutResponse:function(a,b,c,d){return new Promise(function(e,f){BLEPluginStd.writeWithoutResponse(a,b,c,d,e,f)})},stopNotification:function(a,b,c){return new Promise(function(d,e){BLEPluginStd.stopNotification(a,b,c,d,e)})},isConnected:function(a){return new Promise(function(b,c){BLEPluginStd.isConnected(a)})},isEnabled:function(){return new Promise(function(a,b){BLEPluginStd.isEnabled(a,
b)})},enable:function(){return new Promise(function(a,b){BLEPluginStd.enable(a,b)})},showBluetoothSettings:function(){return new Promise(function(a,b){BLEPluginStd.showBluetoothSettings(a,b)})},stopStateNotifications:function(){return new Promise(function(a,b){BLEPluginStd.stopStateNotifications(a,b)})},readRSSI:function(a){return new Promise(function(b,c){BLEPluginStd.readRSSI(a)})}};function BLEPluginPromises(){}function BLE(){}BLE.prototype=new BLEPluginStd;
